services:

  drupal:
    environment:
      SERVER_NAME: :80
    labels:
      traefik.enable: true
      traefik.http.routers.frankenphp-drupal.entrypoints: https
      traefik.http.routers.frankenphp-drupal.rule: Host(`frankenphp-drupal.docker.so`)
      traefik.http.routers.frankenphp-drupal.tls: true
      traefik.http.services.frankenphp-drupal.loadbalancer.server.port: 80
      traefik.docker.network: stonehenge-network
    networks:
      - default
      - stonehenge-network

networks:
  stonehenge-network:
    external: true
