# Drupal with MariaDB
#
# Access via "https://localhost"
#
# During initial Drupal setup, use the following database configuration:
#
# Database type: MySQL, MariaDB, Percona Server, or equivalent 
# Database name: drupal
# Database username: root
# Database password: example
# ADVANCED OPTIONS; Database host: db

services:

  drupal:
    build: .
    volumes:
      - /app/public/modules
      - /app/public/profiles
      - /app/public/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /app/public/sites
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.frankenphp-drupal.entrypoints: https
      traefik.http.routers.frankenphp-drupal.rule: Host(`frankenphp-drupal.docker.so`)
      traefik.http.routers.frankenphp-drupal.tls: true
      traefik.http.services.frankenphp-drupal.loadbalancer.server.port: 80
      traefik.docker.network: stonehenge-network
    environment:
      SERVER_NAME: :80
    networks:
      - default
      - stonehenge-network

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
    restart: always
    networks:
      - default

networks:
  stonehenge-network:
    external: true
