# Drupal with MariaDB
#
# Access via "https://localhost"
#
# During initial Drupal setup,
# Database type: MySQL, MariaDB, Percona Server, or equivalent
# Database name: drupal
# Database username: drupal
# Database password: example
# ADVANCED OPTIONS; Database host: db

version: '3.1'

services:

  drupal:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - /app/public/modules
      - /app/public/profiles
      - /app/public/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /app/public/sites
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: example
    restart: always
